### ISSUE TITLE
Akeneo never stop loading

### ISSUE THREAD

**Issue by Xcreen** [nicolasfl/MappingConnector#2]
Hi,
i have Akeneo 2.3.21-Installation. 
Than i have installed your extension via composer. I added your bundle to the AppKernel.php and cleared the cache.  
When i try to open akeneo, the loading-indicator never disappear and i also receive no error.
![image](https://user-images.githubusercontent.com/26636443/53182358-a3a2e000-35f9-11e9-91d0-2e10f3244107.png)
If i open the Symfony-Profiler and go into Configuration i see that your bundle is registered. But Akeneo simply dont never stop loading and dont throw any error.

If i remove your bundle and clear the cache, everything works again. (but course your bundle is missing than).

Would be nice, if you could look into that.

Thanks :)

**Comment by nicolasfl** [comment]
Hi, 
Thank you for downloading my extension. 
Can you send me the messages in your console? You should get a javascript error.

**Comment by Xcreen** [comment]
Wow that was a fast response!
You´re right i got a js error.
![image](https://user-images.githubusercontent.com/26636443/53183636-f5e50080-35fb-11e9-9afe-fe3aa5b11cc9.png)

I added following route for the Custom-Entity-Bundle (like it readme.md from https://github.com/akeneo-labs/CustomEntityBundle says):
```
pim_customentity:
        prefix: /reference-data
        resource: "@PimCustomEntityBundle/Resources/config/routing.yml"
```

I maybe have to add/rename the same for pim_customentity_index?

**Comment by nicolasfl** [comment]
Have you launched the following command after installing the modules ? 
`rm -rf var/cache; bin/console pim:install:asset; yarn run webpack`

**Comment by Xcreen** [comment]
Thanks! :)
I forgot the: `yarn run webpack`
